### ISSUE TITLE
Homework 3 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-03-abhishekdeore#2]
Dear abhishekdeore -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

Your score is **6.9/10**. I allowed additional time to add narrative but I don't see any results interpretation in your submission. I gave a point to each so that the score was close to 7/10. 

---

### Training and Data: `[7 / 10 points]`

- Reasonable choice for classification: `[6 / 6 points]`
- Narrative: `[1 / 4 points]`
- Feedback: I do not see any result interpretations. 

### Fitting classification models: `[17 / 22 points]`

  - Correct application: `[16 / 16]`
  - Narrative `[1 / 6]`
  - Feedback:  I do not see any result interpretations. 

### Comparing models: `[6 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[1 / 5]`
  - Feedback:  I do not see any result interpretations. 

### Applying chosen model: `[6 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[1 / 5]`
  - Feedback:  I do not see any result interpretations. 

### Comparing decision boundaries: `[19 / 28 points]`

  - Correct application: `[18 / 18]`
  - Narrative: `[1 / 10]`
  - Feedback:  I do not see any result interpretations. 

### Overall: `[14 / 20 points]`

- `[1 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- **Feedback**: I had to change the original .qmd to reproduce your results
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[1 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- **Feedback**: you didn't use many commits and the messages are not descriptive. 
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by abhishekdeore** [comment]
Thank you for the feedback Professor. I will take care regarding the narratives from next time! Thank you.
